// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { AdminProvider } from "@/contexts/AdminContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meus Descontos Online - Melhores Ofertas dos Principais Marketplaces",
  description: "Encontre as melhores promoções e descontos do Mercado Livre, Amazon, Magazine Luiza, Americanas, Shopee e AliExpress em um só lugar. Links de afiliado organizados e atualizados.",
  keywords: "promoções Shopee, descontos Amazon, ofertas Mercado Livre, Magazine Luiza ofertas, Americanas promoções, AliExpress descontos, links afiliado, melhores preços",
  authors: [{ name: "Meus Descontos Online" }],
  openGraph: {
    title: "Meus Descontos Online - Todos os Melhores Descontos em um só Lugar",
    description: "Acesso rápido aos melhores links de afiliado dos principais marketplaces. Economize tempo e dinheiro!",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Meus Descontos Online - Melhores Ofertas",
    description: "Encontre as melhores promoções dos principais marketplaces em um só lugar.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{
          backgroundImage: 'url(https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/e1e92f5f-ef3f-4d6c-8f28-6d80041ea3f4.jpg)',
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundAttachment: 'fixed'
        }}
      >
        <AdminProvider>
          {children}
        </AdminProvider>
      </body>
    </html>
  );
}